In [1]:
import pandas as pd

In [2]:
#csv files are in local drive due to size
df1 = pd.read_csv('202004-citibike-tripdata.csv')
df1.head(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,534,2020-04-01 00:00:15.2800,2020-04-01 00:09:09.8730,3656,E 2 St & Avenue A,40.723077,-73.985836,545,E 23 St & 1 Ave,40.736502,-73.978095,15162,Subscriber,1990,2
1,529,2020-04-01 00:02:28.9430,2020-04-01 00:11:18.3410,3163,Central Park West & W 68 St,40.773407,-73.977825,3301,Columbus Ave & W 95 St,40.791956,-73.968087,42861,Subscriber,1974,1
2,1488,2020-04-01 00:02:56.0900,2020-04-01 00:27:44.2530,3164,Columbus Ave & W 72 St,40.777057,-73.978985,3605,31 Ave & Crescent St,40.765835,-73.926547,35989,Subscriber,1982,1
3,341,2020-04-01 00:03:25.1410,2020-04-01 00:09:06.3190,3827,Halsey St & Broadway,40.685650,-73.915640,3869,Van Buren St & Broadway,40.692000,-73.926170,37548,Subscriber,1996,1
4,2206,2020-04-01 00:05:35.2790,2020-04-01 00:42:21.9080,3890,Grove St & Broadway,40.690470,-73.923511,3058,Lewis Ave & Kosciuszko St,40.692371,-73.937054,39701,Subscriber,1977,1
5,921,2020-04-01 00:05:50.1950,2020-04-01 00:21:11.5120,3697,W 64 St & Thelonious Monk Circle,40.775160,-73.989187,3360,Amsterdam Ave & W 79 St,40.782939,-73.978652,37161,Subscriber,1986,2
6,819,2020-04-01 00:05:57.9940,2020-04-01 00:19:37.2650,297,E 15 St & 3 Ave,40.734232,-73.986923,477,W 41 St & 8 Ave,40.756405,-73.990026,29045,Subscriber,1987,1
7,780,2020-04-01 00:06:41.0220,2020-04-01 00:19:41.9180,3101,N 12 St & Bedford Ave,40.720798,-73.954847,3057,Kosciuszko St & Tompkins Ave,40.691283,-73.945242,41277,Subscriber,1986,2
8,865,2020-04-01 00:10:05.9260,2020-04-01 00:24:30.9420,3244,University Pl & E 8 St,40.731437,-73.994903,3244,University Pl & E 8 St,40.731437,-73.994903,20562,Subscriber,1955,2
9,365,2020-04-01 00:10:27.8050,2020-04-01 00:16:33.1120,3041,Kingston Ave & Herkimer St,40.678907,-73.941428,3059,Pulaski St & Marcus Garvey Blvd,40.693398,-73.939877,36288,Subscriber,1969,0

In [5]:
#csv files are in local drive due to size
df2 = pd.read_csv('201904-citibike-tripdata.csv')
df2.head(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,88,2019-04-01 00:00:14.7410,2019-04-01 00:01:42.8900,2006,Central Park S & 6 Ave,40.765909,-73.976342,2006,Central Park S & 6 Ave,40.765909,-73.976342,36515,Subscriber,1982,1
1,443,2019-04-01 00:00:20.8270,2019-04-01 00:07:44.2920,254,W 11 St & 6 Ave,40.735324,-73.998004,540,Lexington Ave & E 29 St,40.743116,-73.982154,17406,Subscriber,1983,1
2,662,2019-04-01 00:00:30.9960,2019-04-01 00:11:33.2610,3244,University Pl & E 8 St,40.731437,-73.994903,3244,University Pl & E 8 St,40.731437,-73.994903,20775,Subscriber,1988,1
3,86,2019-04-01 00:00:30.9110,2019-04-01 00:01:56.9600,526,E 33 St & 5 Ave,40.747659,-73.984907,474,5 Ave & E 29 St,40.745168,-73.986831,36270,Subscriber,1982,1
4,136,2019-04-01 00:00:32.5930,2019-04-01 00:02:49.3910,461,E 20 St & 2 Ave,40.735877,-73.982050,504,1 Ave & E 16 St,40.732219,-73.981656,36051,Subscriber,1986,1
5,1116,2019-04-01 00:00:52.4840,2019-04-01 00:19:29.1980,3295,Central Park W & W 96 St,40.791270,-73.964839,3367,5 Ave & E 103 St,40.792255,-73.952499,35612,Subscriber,1999,1
6,143,2019-04-01 00:01:14.5420,2019-04-01 00:03:38.4570,3141,1 Ave & E 68 St,40.765005,-73.958185,3372,E 74 St & 1 Ave,40.768974,-73.954823,27759,Subscriber,1963,2
7,790,2019-04-01 00:01:15.7910,2019-04-01 00:14:26.4610,477,W 41 St & 8 Ave,40.756405,-73.990026,461,E 20 St & 2 Ave,40.735877,-73.982050,35711,Subscriber,1992,1
8,189,2019-04-01 00:01:15.8030,2019-04-01 00:04:24.8250,3521,Lenox Ave & W 111 St,40.798786,-73.952300,3553,Frederick Douglass Blvd & W 112 St,40.801694,-73.957145,15023,Subscriber,1987,1
9,566,2019-04-01 00:01:22.9730,2019-04-01 00:10:49.3330,344,Monroe St & Bedford Ave,40.685144,-73.953809,3058,Lewis Ave & Kosciuszko St,40.692371,-73.937054,25716,Subscriber,1986,1

In [6]:
#csv files are in local drive due to size
df3 = pd.read_csv('201804-citibike-tripdata.csv')
df3.head(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,840,2018-04-01 03:07:39.0700,2018-04-01 03:21:39.1280,72,W 52 St & 11 Ave,40.767272,-73.993929,379,W 31 St & 7 Ave,40.749156,-73.991600,31977,Subscriber,1973,1
1,1438,2018-04-01 07:20:02.2150,2018-04-01 07:44:00.5690,72,W 52 St & 11 Ave,40.767272,-73.993929,426,West St & Chambers St,40.717548,-74.013221,21403,Subscriber,1956,1
2,219,2018-04-01 08:11:14.4060,2018-04-01 08:14:53.7880,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,29081,Subscriber,1974,1
3,410,2018-04-01 08:52:32.3730,2018-04-01 08:59:23.2190,72,W 52 St & 11 Ave,40.767272,-73.993929,173,Broadway & W 49 St,40.760683,-73.984527,32130,Subscriber,1983,1
4,485,2018-04-01 09:37:34.3270,2018-04-01 09:45:39.9980,72,W 52 St & 11 Ave,40.767272,-73.993929,3159,W 67 St & Broadway,40.774925,-73.982666,30055,Subscriber,1978,1
5,524,2018-04-01 09:37:36.8160,2018-04-01 09:46:21.0160,72,W 52 St & 11 Ave,40.767272,-73.993929,3159,W 67 St & Broadway,40.774925,-73.982666,33043,Subscriber,1985,1
6,803,2018-04-01 10:54:46.8630,2018-04-01 11:08:09.9150,72,W 52 St & 11 Ave,40.767272,-73.993929,499,Broadway & W 60 St,40.769155,-73.981918,29803,Customer,1969,0
7,810,2018-04-01 10:54:47.0610,2018-04-01 11:08:17.3890,72,W 52 St & 11 Ave,40.767272,-73.993929,499,Broadway & W 60 St,40.769155,-73.981918,30326,Customer,1969,0
8,1133,2018-04-01 10:56:38.3800,2018-04-01 11:15:32.1560,72,W 52 St & 11 Ave,40.767272,-73.993929,459,W 20 St & 11 Ave,40.746745,-74.007756,31917,Subscriber,1988,1
9,2484,2018-04-01 11:14:49.2160,2018-04-01 11:56:13.6380,72,W 52 St & 11 Ave,40.767272,-73.993929,3366,West End Ave & W 107 St,40.802117,-73.968181,27616,Subscriber,1971,1

In [7]:
all_df = [df1,df2,df3]
main_df = pd.concat(all_df)
main_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,534,2020-04-01 00:00:15.2800,2020-04-01 00:09:09.8730,3656,E 2 St & Avenue A,40.723077,-73.985836,545,E 23 St & 1 Ave,40.736502,-73.978095,15162,Subscriber,1990,2
1,529,2020-04-01 00:02:28.9430,2020-04-01 00:11:18.3410,3163,Central Park West & W 68 St,40.773407,-73.977825,3301,Columbus Ave & W 95 St,40.791956,-73.968087,42861,Subscriber,1974,1
2,1488,2020-04-01 00:02:56.0900,2020-04-01 00:27:44.2530,3164,Columbus Ave & W 72 St,40.777057,-73.978985,3605,31 Ave & Crescent St,40.765835,-73.926547,35989,Subscriber,1982,1
3,341,2020-04-01 00:03:25.1410,2020-04-01 00:09:06.3190,3827,Halsey St & Broadway,40.685650,-73.915640,3869,Van Buren St & Broadway,40.692000,-73.926170,37548,Subscriber,1996,1
4,2206,2020-04-01 00:05:35.2790,2020-04-01 00:42:21.9080,3890,Grove St & Broadway,40.690470,-73.923511,3058,Lewis Ave & Kosciuszko St,40.692371,-73.937054,39701,Subscriber,1977,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307538,385,2018-04-30 16:59:18.2040,2018-04-30 17:05:43.2330,3680,E 43 St & 5 Ave,40.754121,-73.980252,501,FDR Drive & E 35 St,40.744219,-73.971212,27431,Subscriber,1984,1
1307539,438,2018-04-30 17:08:20.5350,2018-04-30 17:15:38.6380,3680,E 43 St & 5 Ave,40.754121,-73.980252,3443,W 52 St & 6 Ave,40.761330,-73.979820,17973,Subscriber,1966,1
1307540,1438,2018-04-30 17:21:50.8330,2018-04-30 17:45:49.2940,3680,E 43 St & 5 Ave,40.754121,-73.980252,3492,E 118 St & Park Ave,40.800539,-73.941995,28340,Subscriber,1959,1
1307541,359,2018-04-30 20:24:34.3030,2018-04-30 20:30:33.8730,3680,E 43 St & 5 Ave,40.754121,-73.980252,3236,W 42 St & Dyer Ave,40.758985,-73.993800,19102,Subscriber,1992,2
1307542,508,2018-04-30 21:00:00.2910,2018-04-30 21:08:29.1340,3680,E 43 St & 5 Ave,40.754121,-73.980252,492,W 33 St & 7 Ave,40.750200,-73.990931,21135,Subscriber,1965,1

In [8]:
main_df.to_csv('2018_2019_2020_April.csv')